export type RegisterId = QuadRegister | DoubleRegister | WordRegister | ByteRegister;

export enum QuadRegister {
  rax = 'rax',
  rbx = 'rbx',
  // rcx = 'rcx',
  // rdx = 'rdx',
  // rsi = 'rsi',
  // rdi = 'rdi',
  // rdp = 'rdp',
  // rsp = 'rsp',
  // r8 = 'r8',
  // r9 = 'r9',
  // r10 = 'r10',
  // r11 = 'r11',
  // r12 = 'r12',
  // r13 = 'r13',
  // r14 = 'r14',
  // r15 = 'r15',
}

export enum DoubleRegister {
  eax = 'eax',
  ebx = 'ebx',
  // ecx = 'ecx',
  // edx = 'edx',
  // esi = 'esi',
  // edi = 'edi',
  // edp = 'edp',
  // esp = 'esp',
  // r8d = 'r8d',
  // r9d = 'r9d',
  // r10d = 'r10d',
  // r11d = 'r11d',
  // r12d = 'r12d',
  // r13d = 'r13d',
  // r14d = 'r14d',
  // r15d = 'r15d',
}

export enum WordRegister {
  ax = 'ax',
  bx = 'bx',
  // cx = 'cx',
  // dx = 'dx',
  // si = 'si',
  // di = 'di',
  // dp = 'dp',
  // sp = 'sp',
  // r8w = 'r8w',
  // r9w = 'r9w',
  // r10w = 'r10w',
  // r11w = 'r11w',
  // r12w = 'r12w',
  // r13w = 'r13w',
  // r14w = 'r14w',
  // r15w = 'r15w',
}

export enum ByteRegister {
  al = 'al',
  bl = 'bl',
  // cl = 'cl',
  // dl = 'dl',
  // sil = 'sil',
  // dil = 'dil',
  // dpl = 'dpl',
  // spl = 'spl',
  // r8b = 'r8b',
  // r9b = 'r9b',
  // r10b = 'r10b',
  // r11b = 'r11b',
  // r12b = 'r12b',
  // r13b = 'r13b',
  // r14b = 'r14b',
  // r15b = 'r15b',
}
